vocab_size: 233
vocab: models/definitions/vocab.yml
device: 'cuda'
weights: models/weights/seq2seq/general/2110271046/2110271340.pth

save_file:
    excel: result/s2s/2110271340.xlsx
    text: result/s2s/2110271340.txt

trainer:
    batch_size: 16
    display_cycle: 50  
    valid_cycle: 1000
    iters: 200000
    weight_dir: models/weights/seq2seq/general/

dataset:    
    name: 'test'
    data_root: ./dataset/images/
    train_annotation: ./dataset/annotation/general/train.txt
    valid_annotation: ./dataset/annotation/general/val.txt
    test_annotation: ./dataset/annotation/vtp/test.txt
    expected_height: 64
    image_min_width: 64
    image_max_width: 2048

seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    image_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.0003
    pct_start: 0.1

dataloader:
    num_workers: 4
    pin_memory: True

aug:
    image_aug: True
    masked_language_model: True

backbone: resnet50
cnn_args:
  ss: [[2, 2],
       [2, 1],
       [2, 1],
       [2, 1],
       [1, 1]]
  hidden: 256