vocab: models/definitions/vocab.yml
device: 'cuda'
weights: models/weights/seq2seq/base_s2s.pth

save_file:
    excel: result_s2s.xlsx
    text: wrong_case_s2s.txt

trainer:
    batch_size: 16
    display_cycle: 50  
    valid_cycle: 1000
    iters: 100000
    weight_dir: models/weights/seq2seq/

dataset:    
    name: 'vtp'
    data_root: ./dataset/images/
    train_annotation: ./dataset/annotation/vtp/train.txt
    valid_annotation: ./dataset/annotation/vtp/val.txt
    test_annotation: ./dataset/annotation/vtp/test.txt
    expected_height: 32
    image_min_width: 32
    image_max_width: 2048

seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    image_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.0002
    pct_start: 0.1

dataloader:
    num_workers: 4
    pin_memory: True

aug:
    image_aug: True
    masked_language_model: True

backbone: vgg19
cnn_args:
    pretrained: False
    ss: [[2, 2],
         [2, 2],
         [2, 1],
         [2, 1],
         [2, 1]]
    ks: [[2, 2],
         [2, 2],
         [2, 1],
         [2, 1],
         [2, 1]]
    hidden: 256
    dropout: 0.1